import Head from "next/head";
import Hero from "../components/Hero";
import Layout from "../components/Layout"
import Menu from "../components/Menu";
import Services from "../components/Services";
import { client } from "../lib/client";
import css from "../styles/home.module.css"
export default function Home({foodItems}) {

  return (
      <Layout>
        <div className={css.container}>
          <Head>
            <title>Swiato</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/Logo.png" size="64x64" />
          </Head>
          {/* body */}
          <main>
            <Hero/>  
            <Services/>  
            <Menu foodItems={foodItems}/>
          </main>
        </div>
      </Layout>
  );
}

export const getServerSideProps = async () => {
  const query = '*[_type == "food"]';
  const foodItems = await client.fetch(query);
  return {
    props :{
      foodItems
    }
  }
}

